#!/usr/bin/env ruby
require_relative 'lib/cheer'
# This file is for I/O, and delegates logic to our tested classes (in lib).

puts "Hello, what's your name?"
until Cheer.valid_name?(name)
  puts "Sorry, please try again."
  name = gets.chomp
end
name = gets
puts Cheer.for_person(name)
# THIS IS COMMENTED AS AN EXAMPLE ONLY
# Don't commit commented out code!
puts "Hey #{name}, what's your birthday? (mm/dd)"
# birthday_string = gets
# puts Cheer.for_birthday(birthday_string)
